#!/usr/bin/env python3
"""Generate the function call graph for docs/execution.md.

Usage:
    python scripts/gen_callgraph.py            # rewrite docs/callgraph.md
    python scripts/gen_callgraph.py --check    # exit 1 if docs/callgraph.md is out of date

Needs: pip install pyan3  (tested with pyan3 2.8.1 on Python 3.13)

The output is a sorted list of "caller -> callee" lines. It holds no file
paths, so it is identical on every machine and safe to compare in CI.
"""
import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
EDGE = re.compile(r'"([^"]+)"\s*->\s*"([^"]+)"')
NODE = re.compile(r'"([^"]+)"\s*\[label=.*?tooltip="([^"\\]+)')
HEADER = (
    "# Function call graph\n\n"
    "Auto-generated by `scripts/gen_callgraph.py`. Do not edit by hand.\n"
    "Each line reads: caller -> callee.\n\n"
)


def build(src: Path, root: Path) -> str:
    files = sorted(str(p) for p in src.rglob("*.py"))
    if not files:
        sys.exit(f"No Python files found under {src}")
    cmd = [sys.executable, "-m", "pyan", *files, "--root", str(root),
           "--uses", "--no-defines", "--dot"]
    run = subprocess.run(cmd, capture_output=True, text=True)
    if run.returncode != 0:
        sys.exit(f"pyan3 failed:\n{run.stderr}")
    names = dict(NODE.findall(run.stdout))  # node id -> full dotted name
    edges = sorted({(names.get(a, a), names.get(b, b))
                    for a, b in EDGE.findall(run.stdout)})
    body = "\n".join(f"{a} -> {b}" for a, b in edges) or "(no calls found)"
    return f"{HEADER}```\n{body}\n```\n\n{len(edges)} call edges.\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="src/clientprofit")
    ap.add_argument("--root", default="src")
    ap.add_argument("--out", default="docs/callgraph.md")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    out = REPO / args.out
    text = build(REPO / args.src, REPO / args.root)
    if args.check:
        if not out.exists() or out.read_text() != text:
            sys.exit(f"{args.out} is out of date. Run: python scripts/gen_callgraph.py")
        print(f"{args.out} matches the code.")
        return
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
